server:
  port: 9002
#服务名称 service-hi
spring:
  application:
    name: service-hi
#注册中心请求地址，请求接口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka
      #注册是否开启
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30